stages:
- name: compile
  steps:
  - runScriptConfig:
      image: maven
      shellScript: mvn -B -DskipTests clean package
- name: deliver
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: '#!/usr/bin/env bash'
timeout: 600
