stages:
- name: compile
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: mvn -B -DskipTests clean package
- name: deliver
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: ls
timeout: 60
