stages:
- name: compile
  steps:
  - runScriptConfig:
      image: maven
      shellScript: mvn -B -DskipTests clean package
- name: deliver
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: |
        #!/usr/bin/env bash
        echo 'The following Maven command installs your Maven-built Java application'
        echo 'into the local Maven repository, which will ultimately be stored in'
        echo 'Jenkins''s local Maven repository (and the "maven-repository" Docker data'
        echo 'volume).'
timeout: 600
